server:
  port: 8081
spring:
  application:
    name: inmobi
  datasource:
    url: jdbc:h2:mem:inmobiDb
    driver-class-name: org.h2.Driver
    username: sa
    password: Password#1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: db/migration

jwt:
  secret: ${JWT_SECRET:X7qk+UGb4wGFD8aw8mb3p1mZMYNnZCCuFGolRxO6xRg=}
  expiration: 86400000

app:
  probability: 5
  turn: 5
  price: 2000
  domainUrl: http://localhost:8081